/*
 * THIS FILE IS AUTOGENERATED, DO NOT EDIT!
 *
 * generated by gattdbgen from depend_Release_CSR101x_A05/battery_service_db.db_
 */

#include "depend_Release_CSR101x_A05/battery_service_db.h"

/* GATT database */
uint16 gattDatabase[] = {
    /* 0001: Primary Service 180f */
    0x0002, 0x0f18,
    /* 0002: Characteristic Declaration 2a19 */
    0x3005, 0x1203, 0x0019, 0x2a00,
    /* 0003: . */
    0xd401, 0x0000,
    /* 0004: Client Characteristic Configuration */
    0x6400,
};

uint16 *GattGetDatabase(uint16 *len)
{
    *len = sizeof(gattDatabase);
    return gattDatabase;
}

/* End-of-File */
